title: WikiCite
description: This is no official homepage of WikiCite but a minimal, general entry point. 
    
pages:
 - path: publications

#twitter_username: '@wikicite'
github_username: 'wikicite'

theme: minima
